### ISSUE TITLE
Incompatibility with the latest version of Acorn

### ISSUE THREAD

**Issue by cataras** [tombroucke/sage-html-forms-export-submissions#1]
It seems that your script doesn't work with Acorn 4. 

I'm getting the following error: 

> In SageHtmlFormsExportSubmissionsServiceProvider.php line 8:
>                                                                                                                                                                 
> **Class Otomaties\SageHtmlFormsExportSubmissions\Providers\SageHtmlFormsExportSubmissionsServiceProvider cannot extend final class Roots\Acorn\ServiceProvider**.  

Are you still using this script? Does it work for you?

**Comment by tombroucke** [comment]
Fixed in [1.4.0](https://github.com/tombroucke/sage-html-forms-export-submissions/releases/tag/1.4.0)

**Comment by cataras** [comment]
Great work. Thanks a lot @tombroucke. How do you get the export to work? I can't see anything...

**Comment by tombroucke** [comment]
> Great work. Thanks a lot @tombroucke. How do you get the export to work? I can't see anything...

After installation, there is an extra `Export submissions` tab when you open / edit the contact form. When you hover over the contact form in HTML Forms > All Forms, there is also a `Export submissions` quick link.

You might have to run `wp acorn optimize:clear` after installation.

**Comment by cataras** [comment]
Great, thanks! I think I needed to run `wp acore optimize:clear`. Now it works. Many thanks @tombroucke!
